---
# _config.yml for Carlos Cruz's GitHub Portfolio using Minimal Mistakes theme

# Site settings
title: "Portfolio"
#name: "Carlos A. Cruz"
#description: "Computational Scientist | SSAI Inc and NASA GSFC | GMU"
#logo: "/assets/img/photo.jpg"
#url: "https://cacruz.github.io"
#baseurl: "" # GitHub Pages project root

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Author profile for sidebar
author:
  name: "Carlos A. Cruz"
  avatar: "/assets/img/photo.jpg"
  bio: "Lead software engineer of NU-WRF and eViz. Adjunct professor at GMU."
  location: "Maryland, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/cacruz"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/carlos-cruz-0844b79"
    - label: "Resume (PDF)"
      icon: "fas fa-file-pdf"
      url: "/assets/files/carlos_cruz_resume.pdf"
    - label: "CV (PDF)"
      icon: "fas fa-file-pdf"
      url: "/assets/files/carlos_cruz_cv.pdf"

# Sidebar configuration
sidebar:
  nav: "navigation"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-include-cache
